export const iconsProps = [
  {name: "FaceTime", type: "facetime"},
  {name: "AppStore", type: "appstore"},
  {name: "Books", type: "books"},
  {name: "Mail", type: "mail"},
  {name: "Settings", type: "settings"},
  {name: "Stocks", type: "stocks"},
  {name: "Weather", type: "weather"},
  {name: "Notes", type: "notes"},
  {name: "Files", type: "files"},
  {name: "Calculator", type: "calculator"},
  {name: "Camera", type: "camera"},
  {name: "Health", type: "health"},
  {name: "News", type: "news"},
  {name: "Wallet", type: "wallet"},
  {name: "Instagram", type: "instagram"},
  {name: "VK", type: "vk"},
  {name: "Netflix", type: "netflix"},
  {name: "Spotify", type: "spotify"},
  {name: "VLC", type: "vlc"},
  {name: "Telegram", type: "telegram"},
  {name: "WhatsApp", type: "whatsapp"},
  {name: "YouTube", type: "youtube"},
  {name: "AliExpress", type: "aliexpress"},
  {name: "Twitter", type: "twitter"},
];
